import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "./stories/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Earthy color palette
        terracotta: {
          50: "#fdf6f3",
          100: "#fae8e0",
          200: "#f5d0c1",
          300: "#ebb197",
          400: "#e08b6d",
          500: "#d4704d",
          600: "#c25a3d",
          700: "#a14734",
          800: "#853d30",
          900: "#6f362b",
        },
        sage: {
          50: "#f6f7f4",
          100: "#e9ebe3",
          200: "#d4d8c9",
          300: "#b6bda6",
          400: "#98a184",
          500: "#7d8768",
          600: "#636b52",
          700: "#4f5543",
          800: "#424639",
          900: "#383c31",
        },
        sand: {
          50: "#fafaf9",
          100: "#f5f4f1",
          200: "#e9e7e0",
          300: "#d8d4c8",
          400: "#c4bfaf",
          500: "#afa896",
          600: "#8f8a7a",
          700: "#767263",
          800: "#625f54",
          900: "#524f47",
        },
        clay: {
          50: "#faf7f5",
          100: "#f2ebe5",
          200: "#e5d6ca",
          300: "#d3b9a5",
          400: "#bf9a7e",
          500: "#a97d5f",
          600: "#8f6750",
          700: "#765444",
          800: "#62463b",
          900: "#523c33",
        },
        cream: {
          50: "#fdfcfb",
          100: "#faf8f5",
          200: "#f5f1ea",
          300: "#ede7dc",
          400: "#e3d9c9",
          500: "#d6c8b3",
          600: "#b8a68f",
          700: "#9a8874",
          800: "#7f7161",
          900: "#695e51",
        },
        // Semantic colors
        background: "var(--color-background)",
        foreground: "var(--color-foreground)",
        primary: {
          DEFAULT: "var(--color-primary)",
          foreground: "var(--color-primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--color-secondary)",
          foreground: "var(--color-secondary-foreground)",
        },
        accent: {
          DEFAULT: "var(--color-accent)",
          foreground: "var(--color-accent-foreground)",
        },
        muted: {
          DEFAULT: "var(--color-muted)",
          foreground: "var(--color-muted-foreground)",
        },
        card: {
          DEFAULT: "var(--color-card)",
          foreground: "var(--color-card-foreground)",
        },
        popover: {
          DEFAULT: "var(--color-popover)",
          foreground: "var(--color-popover-foreground)",
        },
        border: "var(--color-border)",
        input: "var(--color-input)",
        ring: "var(--color-ring)",
        destructive: {
          DEFAULT: "var(--color-destructive)",
          foreground: "var(--color-destructive-foreground)",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)", "Inter", "system-ui", "sans-serif"],
        display: [
          "var(--font-display)",
          "Playfair Display",
          "Georgia",
          "serif",
        ],
      },
      fontSize: {
        xs: ["0.75rem", { lineHeight: "1rem" }],
        sm: ["0.875rem", { lineHeight: "1.25rem" }],
        base: ["1rem", { lineHeight: "1.5rem" }],
        lg: ["1.125rem", { lineHeight: "1.75rem" }],
        xl: ["1.25rem", { lineHeight: "1.75rem" }],
        "2xl": ["1.5rem", { lineHeight: "2rem" }],
        "3xl": ["1.875rem", { lineHeight: "2.25rem" }],
        "4xl": ["2.25rem", { lineHeight: "2.5rem" }],
        "5xl": ["3rem", { lineHeight: "1" }],
        "6xl": ["3.75rem", { lineHeight: "1" }],
        "7xl": ["4.5rem", { lineHeight: "1" }],
        "8xl": ["6rem", { lineHeight: "1" }],
        "9xl": ["8rem", { lineHeight: "1" }],
      },
      spacing: {
        "0": "0",
        "1": "0.25rem",
        "2": "0.5rem",
        "3": "0.75rem",
        "4": "1rem",
        "5": "1.25rem",
        "6": "1.5rem",
        "8": "2rem",
        "10": "2.5rem",
        "12": "3rem",
        "16": "4rem",
        "20": "5rem",
        "24": "6rem",
        "32": "8rem",
      },
      borderRadius: {
        none: "0",
        sm: "0.25rem",
        base: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        sm: "0 1px 2px 0 rgba(82, 79, 71, 0.05)",
        DEFAULT:
          "0 1px 3px 0 rgba(82, 79, 71, 0.1), 0 1px 2px -1px rgba(82, 79, 71, 0.1)",
        md: "0 4px 6px -1px rgba(82, 79, 71, 0.1), 0 2px 4px -2px rgba(82, 79, 71, 0.1)",
        lg: "0 10px 15px -3px rgba(82, 79, 71, 0.1), 0 4px 6px -4px rgba(82, 79, 71, 0.1)",
        xl: "0 20px 25px -5px rgba(82, 79, 71, 0.1), 0 8px 10px -6px rgba(82, 79, 71, 0.1)",
        "2xl": "0 25px 50px -12px rgba(82, 79, 71, 0.25)",
        inner: "inset 0 2px 4px 0 rgba(82, 79, 71, 0.05)",
        none: "none",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "fade-out": {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
        "slide-in-from-top": {
          from: { transform: "translateY(-100%)" },
          to: { transform: "translateY(0)" },
        },
        "slide-in-from-bottom": {
          from: { transform: "translateY(100%)" },
          to: { transform: "translateY(0)" },
        },
        "slide-in-from-left": {
          from: { transform: "translateX(-100%)" },
          to: { transform: "translateX(0)" },
        },
        "slide-in-from-right": {
          from: { transform: "translateX(100%)" },
          to: { transform: "translateX(0)" },
        },
        "zoom-in": {
          from: { transform: "scale(0.95)", opacity: "0" },
          to: { transform: "scale(1)", opacity: "1" },
        },
        "zoom-out": {
          from: { transform: "scale(1)", opacity: "1" },
          to: { transform: "scale(0.95)", opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.2s ease-out",
        "fade-out": "fade-out 0.2s ease-out",
        "slide-in-from-top": "slide-in-from-top 0.3s ease-out",
        "slide-in-from-bottom": "slide-in-from-bottom 0.3s ease-out",
        "slide-in-from-left": "slide-in-from-left 0.3s ease-out",
        "slide-in-from-right": "slide-in-from-right 0.3s ease-out",
        "zoom-in": "zoom-in 0.2s ease-out",
        "zoom-out": "zoom-out 0.2s ease-out",
      },
      transitionTimingFunction: {
        "ease-spring": "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      screens: {
        xs: "475px",
      },
      container: {
        center: true,
        padding: {
          DEFAULT: "1rem",
          sm: "2rem",
          lg: "4rem",
          xl: "5rem",
          "2xl": "6rem",
        },
      },
    },
  },
  plugins: [],
};

export default config;
